server:
  port: 8086
spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 1
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:db/t.db
    username: root
    password: 123456
